# Generated by Django 3.2.12 on 2023-05-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='article_id',
            new_name='article',
        ),
    ]
