# Generated by Django 3.2.12 on 2023-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_article_id_like_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.TextField(),
        ),
    ]
