# Generated by Django 3.2.12 on 2023-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.TextField()),
                ('overview', models.TextField()),
                ('release_date', models.TextField()),
                ('poster_path', models.TextField()),
            ],
        ),
    ]
