# Dockerfile for front/vue_project Vue project
# Base image
FROM node:14

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm i
# RUN npm ci

# Copy project files
COPY . .

# Build for production
# RUN npm run build

# Expose port
EXPOSE 8080

# Start development server
CMD ["npm", "run", "serve"]
